import type { EditorThemeClasses } from 'lexical';

export const editorTheme: EditorThemeClasses = {
  root: 'obelisk-editor-root',
  paragraph: 'obelisk-paragraph',
  heading: {
    h1: 'obelisk-h1',
    h2: 'obelisk-h2',
    h3: 'obelisk-h3',
    h4: 'obelisk-h4',
    h5: 'obelisk-h5',
    h6: 'obelisk-h6',
  },
  list: {
    nested: {
      listitem: 'obelisk-nested-listitem',
    },
    ol: 'obelisk-ol',
    ul: 'obelisk-ul',
    listitem: 'obelisk-listitem',
    listitemChecked: 'obelisk-listitem-checked',
    listitemUnchecked: 'obelisk-listitem-unchecked',
  },
  quote: 'obelisk-quote',
  code: 'obelisk-code',
  codeHighlight: {
    atrule: 'obelisk-tokenAttr',
    attr: 'obelisk-tokenAttr',
    boolean: 'obelisk-tokenProperty',
    builtin: 'obelisk-tokenSelector',
    cdata: 'obelisk-tokenComment',
    char: 'obelisk-tokenSelector',
    class: 'obelisk-tokenFunction',
    'class-name': 'obelisk-tokenFunction',
    comment: 'obelisk-tokenComment',
    constant: 'obelisk-tokenProperty',
    deleted: 'obelisk-tokenProperty',
    doctype: 'obelisk-tokenComment',
    entity: 'obelisk-tokenOperator',
    function: 'obelisk-tokenFunction',
    important: 'obelisk-tokenVariable',
    inserted: 'obelisk-tokenSelector',
    keyword: 'obelisk-tokenAttr',
    namespace: 'obelisk-tokenVariable',
    number: 'obelisk-tokenProperty',
    operator: 'obelisk-tokenOperator',
    prolog: 'obelisk-tokenComment',
    property: 'obelisk-tokenProperty',
    punctuation: 'obelisk-tokenPunctuation',
    regex: 'obelisk-tokenVariable',
    selector: 'obelisk-tokenSelector',
    string: 'obelisk-tokenSelector',
    symbol: 'obelisk-tokenProperty',
    tag: 'obelisk-tokenProperty',
    url: 'obelisk-tokenOperator',
    variable: 'obelisk-tokenVariable',
  },
  link: 'obelisk-link',
  text: {
    bold: 'obelisk-text-bold',
    italic: 'obelisk-text-italic',
    strikethrough: 'obelisk-text-strikethrough',
    underline: 'obelisk-text-underline',
    underlineStrikethrough: 'obelisk-text-underline-strikethrough',
    code: 'obelisk-text-code',
    subscript: 'obelisk-text-subscript',
    superscript: 'obelisk-text-superscript',
  },
  table: 'obelisk-table',
  tableCell: 'obelisk-table-cell',
  tableCellHeader: 'obelisk-table-cell-header',
  tableRow: 'obelisk-table-row',
  tableAddColumns: 'obelisk-table-add-columns',
  tableAddRows: 'obelisk-table-add-rows',
};
